# Uses a pre-built image from nvidia, then we install Flower
# We also install dependencies for a very exciting future project

# check this repo to learn more about the image below: https://github.com/dusty-nv/jetson-containers
FROM nvcr.io/nvidia/l4t-pytorch:r34.1.0-pth1.12-py3

RUN mkdir /app
WORKDIR /app

RUN echo "done!"
